# Generated by Django 6.0.2 on 2026-03-16 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0002_remove_producto_sku'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='descripcion_ia',
            field=models.TextField(blank=True, null=True),
        ),
    ]
