# Generated by Django 6.0.2 on 2026-03-16 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0003_producto_descripcion_ia'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='precio_sugerido_ia',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
    ]
