# Generated by Django 6.0.2 on 2026-02-12 00:11

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('producto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('IN', 'Entrada (Compra)'), ('OUT', 'Salida (Venta)')], max_length=3)),
                ('cantidad', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('precio_unitario', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('nota', models.CharField(blank=True, max_length=255)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='producto.producto')),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
    ]
