# Generated by Django 6.0.2 on 2026-02-15 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movimiento', '0002_alter_movimiento_tipo_venta_pagoventa'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimiento',
            name='anulada',
            field=models.BooleanField(default=False),
        ),
    ]
