# Generated by Django 6.0.2 on 2026-02-16 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movimiento', '0003_movimiento_anulada'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movimiento',
            name='anulada',
        ),
    ]
