# Generated by Django 6.0.2 on 2026-03-16 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movimiento', '0003_movimiento_anulada'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='analisis_riesgo_ia',
            field=models.TextField(null=True),
        ),
    ]
