# Generated by Django 6.0.2 on 2026-05-21 16:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movimiento', '0004_venta_analisis_riesgo_ia'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='cliente',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='pagoventa',
            name='fecha',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='venta',
            name='fecha',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
