# Generated by Django 6.0.2 on 2026-06-06 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movimiento', '0005_venta_cliente_alter_pagoventa_fecha_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='anulada',
            field=models.BooleanField(default=False),
        ),
    ]
