# Generated by Django 6.0.2 on 2026-09-28 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movimiento', '0007_remove_analisis_riesgo_ia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimiento',
            name='tipo',
            field=models.CharField(choices=[('IN', 'Entrada (Compra)'), ('OUT', 'Salida (No usar)'), ('ADJ', 'Baja / Ajuste de inventario')], default='IN', max_length=3),
        ),
    ]
