# Generated by Django 6.0.2 on 2026-02-16 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movimiento', '00034_movimiento_anulada'),
        ('movimiento', '0003_movimiento_anulada'),
    ]

    operations = [
    ]
